name: Scan container image

on:

  schedule:
  - cron: 18 13 26 * *

  workflow_dispatch: {}

defaults:
  run:
    shell: bash

jobs:

  scan:
    runs-on: ubuntu-latest

    steps:

    - uses: azure/container-scan@v0
      with:
        image-name: ghcr.io/yrro/rsync.net-exporter:latest
